# Generated by Django 3.2 on 2023-12-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231228_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionretailsales',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Purchase Amount (USD)'),
        ),
    ]
