# Generated by Django 3.2 on 2023-12-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_fashionretailsales_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fashionretailsales',
            options={'ordering': ('-id',)},
        ),
    ]
